bbatsov/zenburn-emacs

zenburn-theme.el
Replace the somewhat ~~jarring~~ surprising default colors with more zenburnesque ones.
=> Add helm-swoop faces

zenburn-theme.el
Added faces for circe. Based off of the existing erc faces as much as possible.
=> Add circe faces

zenburn-theme.el
Fix typo in circe-highlight-nick-face, updated circe-highlight-nick-face face.
=> Correct typo in face name

zenburn-theme.el
Added faces for the hydra color faces.  Open to suggestions on amaranth which is sort of a purply-red color in default hydra. I felt zenburn-red-3 fit the best, feel the others are pretty spot on.
=> Added hydra faces

zenburn-theme.el
I couldn't tell if the basic coloring section had any sort of order, so I put this ad the end.
Closes #198
=> Copy tooltip face from company-tooltip

zenburn-theme.el
This should be merged after I have released version `2.1.0` which will happen on the 1th of July, but not earlier.
This is not quite ready yet, some fine-tuning is still required.
=> Support version 2.1.0 of Magit

zenburn-theme.el
I made my best to add the @abo-abo package I love: [swiper](https://github.com/abo-abo/swiper/) which face comes from ivy.  I tried to mimmics the ido faces.
I also added ruler-mode.
I hope it fit your tastes!
=> Added support for ruler-mode and swiper package

zenburn-theme.el
=> Add face for helm-match

zenburn-theme.el
=> Add missing Anzu faces

zenburn-theme.el
Background face taken from `avy`, should look fine.
=> Add ace-window support

zenburn-theme.el
=> Add Lispy support

zenburn-theme.el
=> Add dired-async support

zenburn-theme.el
Face added in the latest updates to `dired-async`.
=> Add dired-async-failures face

zenburn-theme.el
Faces for the Elfeed log buffer.
=> Add elfeed-log faces

zenburn-theme.el
=> pdf-tools midnignt mode

zenburn-theme.el
Add support for the neotree plugin: https://melpa.org/#/neotree
=> Add neotree support

zenburn-theme.el
Exactly the same as in https://github.com/bbatsov/solarized-emacs/pull/233
=> Stop overriding cider overlay foreground

zenburn-theme.el
Might still be missing some -xact faces but these are the most obvious ones
=> Add missing ledger-mode faces

zenburn-theme.el
Support for the [visual-regexp](https://github.com/benma/visual-regexp.el) package.
=> Add visual-regexp support

zenburn-theme.el
Add support for the built-in re-builder package.
=> Add support for re-builder

zenburn-theme.el
[Eros](https://github.com/xiongtx/eros) is a result overlay package for Emacs Lisp inspired by CIDER.
=> Add face for eros

zenburn-theme.el
This adds support for the `debbugs` package.
=> Debbugs suport

zenburn-theme.el
=> Fix background in Gnus

zenburn-theme.el
Add zenburn colors for `merlin-mode`.
=> Add faces for merlin-mode

zenburn-theme.el
I'm not a designer, so feel free to adjust.
=> Add realgud settings

zenburn-theme.el
Simply underline the references as these are all links.
=> Add faces for org-ref

zenburn-theme.el
Add colours for [selectrum](https://github.com/raxod502/selectrum). Similar colours to ivy.
=> Add selectrum colours

CHANGELOG.md, zenburn-theme.el
This PR fixes https://github.com/bbatsov/zenburn-emacs/issues/347
For detailed screenshots, please kindly refer to the issue with the link above.
=> [Enhancement] Add support for highlight-symbol & highlight-thing

zenburn-theme.el
This PR proposes a fix to issue #359.
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!
=> Fix text-scale-adjust with display-line-numbers-mode.

CHANGELOG.md, zenburn-theme.el
=> Add support for ansi-color faces

CHANGELOG.md, zenburn-theme.el
Add support for [Corfu](https://github.com/minad/corfu)
=> Corfu theme
