bbatsov/zenburn-emacs

- zenburn-theme.el
[`racket-mode`](https://github.com/greghendershott/racket-mode/) defines additional faces for symbols, numbers and other things (like `#t` and `#f`), these clash with default zenburn colours.
> Add racket-mode #:keywords and symbol face custs.

- zenburn-theme.el
The new face was added in
https://github.com/abo-abo/avy/commit/755c25a89bf01f1ad07c6ebd1bde08e1c5474794
Since it's the color of the overlay of the first char, make it a bit
lighter than `avy-lead-face'.
> Add support for new face `avy-lead-face-0'

- zenburn-theme.el
magit-diff-lines-heading references zenburn-black which is an undefined
variable. Replacing it with zenburn-bg+2 as per
https://github.com/magit/magit/blob/master/lisp/magit-diff.el#L313-L332
it appears that magit-diff-lines-heading is supposed to be the inverse
of magit-diff-hunk-heading-selection.
> Undefined variable zenburn-black in magit 2.1 face

- zenburn-theme.el
I've been using the following color scheme with [context-coloring](https://github.com/jacksonrayhamilton/context-coloring) for several months. It would be beneficial if zenburn users could automatically have this color scheme set up when they use context-coloring (especially since zenburn is also featured in the screenshot for the package).
context-coloring applies colors to variables based on their scope. A rainbow illustrates increasingly-higher scope levels. The colors I choose should be unambiguous when juxtaposed against other colors in the rainbow, and against syntactic elements like comments, strings and docstrings.
> Add support for context-coloring

- zenburn-theme.el
Add support for new face `company-tooltip-annotation-selection`.
With https://github.com/company-mode/company-mode/commit/e5177c91887dda193309a60c4096533ce76352f1, the annotation background needs to be set separately.
See discussion here: https://github.com/company-mode/company-mode/issues/445
> Add new company-tooltip-annotation-selection face

- zenburn-theme.el
- Uses different colors for a more pleasing look when `diff-hl-draw-borders`
set to true.
- Also removes `diff-hl-unknown`, which doesn't appear to be used by
diff-hl anymore.
Screenshot attached.
> Update diff-hl colors.

- zenburn-theme.el
These faces correspond to some metadata in `org-mode` documents. They are currently unmodified in the theme, and default to `pale turquoise` (according to `org-faces.el`). This PR makes a very small change and updates the faces to their closest Zenburn equivalent, `zenburn-blue`, for the sake of consistency.
Before and after screenshots:
Anecdotally, I have noticed that the difference is more stark on Windows, and with other fonts/sizes.
> Add faces for org-document-* in org-mode files.

- README.md
- zenburn-theme.el
If a user wants to tweak the theme by changing just a few colours, they
can now do so by defining new values for just that subset in the new
"zenburn-override-colors-alist" variable.
This improves over the previous approach of having to completely
re-specify the full list of colours, which both obscures the actual
overrides among the unchanged defaults, and risks breaking when new
colours are added to the default theme without the user updating their
definition.
For example, to tweak just the lighter background colours, a user
might add to their `init.el`:
```elisp
(defvar zenburn-override-colors-alist
'(("zenburn-bg+05" . "#282828")
("zenburn-bg+1"  . "#2F2F2F")
("zenburn-bg+2"  . "#3F3F3F")
("zenburn-bg+3"  . "#4F4F4F")))
(load-theme 'zenburn t)
```
> Add a mechanism to override a subset of the theme's colours

- README.md
The existing zenburn link redirects to Jani's blog
[http://kippura.org/](http://kippura.org/).
Changed it to link to `zenburnpage`.
Also added a link to Jani Nurminen's github profile.
> Fix the link to Vim's zenburn page

- zenburn-theme.el
Starting with Emacs 25.1 symbol names in Info pages are displayed with a fixed-pitch font. This commit changes the Info-quoted face to use a style little more consistent with Elisp syntax highlight.
> Change the new Info-quoted face introduced in Emacs 25.1

- zenburn-theme.el
Adapt hard-coded [irfc](https://www.emacswiki.org/emacs/Irfc) faces to zenburn palette.
> Add irfc support

- zenburn-theme.el
New Anzu update introduced a face for the mode line indicator when there is no matches.
> Add no match color for the Anzu mode line indicator.

- zenburn-theme.el
The faces were mistakenly listed as built-in in PR #256.
> Demote irfc faces to third-party section

- zenburn-theme.el
Hi Bozhidar,
I've done some minor changes to your theme in order to fix two faces related to the emacs' popup  menu. The screenshots below show the use of the popup menu in a python-mode (using [jedi](http://tkf.github.io/emacs-jedi/latest/#jedi:server-command)). Please find below the popup menus before and after the changes:
**Before**
**After**
Regards,
Davide
> Fix pop menu colors (i.e. needed in jedi)

- zenburn-theme.el
Playlist view before (default settings, album and artist faces are unthemed):
And with the new album and artist faces:
The Zenburn colours chosen in these cases are similar to the default ones provided by the package. Let me know if there is any objection to this approach.
> Add support for album, artist, and mark faces for mingus.

- zenburn-theme.el
Adapt [regex-tool](https://github.com/jwiegley/regex-tool) faces to zenburn palette.
> Add regex-tool support

- zenburn-theme.el
Colourise `man` and `woman` modes.
> Add man and woman support

- zenburn-theme.el
Adapt `hi-lock` faces to the `zenburn` palette.
> Add hi-lock support

- zenburn-theme.el
Colourise missing [ivy](https://github.com/abo-abo/swiper) face `ivy-cursor` and sort ivy faces by name.
> Extend ivy faces

- zenburn-theme.el
Adapt `eww` certificate status faces to `zenburn` palette via standard faces.
> Add eww certificate support

- zenburn-theme.el
Adapt [`git-annex`](https://github.com/jwiegley/git-annex-el) `dired` faces to `zenburn` palette.
> Add git-annex support

- zenburn-theme.el
Adapt those [`sx`](https://github.com/vermiculus/sx.el) faces not based on `font-lock` ones to the `zenburn` palette.
> Add sx support

- zenburn-theme.el
This is to add support for identifier highlights in `go-guru` as per https://github.com/bbatsov/zenburn-emacs/issues/282.
I have no strong opinion on the colors. I just picked something I thought would be noticeable but not too garish. I'm happy to change it.
Also, I'm not sure whether it's recommended to continue to inherit from the `highlight` face, but that's what I did. I'm happy to change this as well.
Before:
After:
> Add `go-guru` support

- zenburn-theme.el
Adapt [`hackernews`](https://github.com/clarete/hackernews.el) faces to `zenburn` palette.
> Add hackernews support

- zenburn-theme.el
The faces referenced previously in `zenburn` [were recently](https://github.com/clarete/hackernews.el/commit/87a1fab5082ffa42fc4140083f5676f2d918dcc5) declared obsolete face aliases in `hackernews`.
> Update hackernews face names

- zenburn-theme.el
This sets the foreground color for "font-latex-script-char-face" to "zenburn-orange", the standard color for LaTeX math.  Before, no foreground color was set for this, resulting in bright red "_" and "^" symbols; cf. https://www.gnu.org/software/auctex/manual/auctex/Fontification-of-math.html.
> Fix bright red _ and ^ in LaTeX math mode

- zenburn-theme.el
```
The old face `git-commit-comment-branch' was replaced
with two new faces `git-commit-comment-branch-local'
and `git-commit-comment-branch-remote'.
Keep the old face around for a while until "everyone"
has updated, but at least until the next `git-commit'
release.
```
> Update git-commit faces

- zenburn-theme.el
Not 100% sure on the colour selection, suggestions welcome!
(I've only changed the background, but [magit also changes fg colour](https://github.com/magit/magit/blob/master/lisp/magit-diff.el)).
> Add zenburn red/green for magit diff remove/add blocks

- zenburn-theme.el
They are variables, not faces, so they should go under
custom-theme-set-variables, not custom-theme-set-faces (thanks basil-conto).
> Move company-quickhel to the correct section

- zenburn-theme.el
This is the minimum to make cperl in zenburn look less jarring for the
sample file chosen.  There may be more later.
This closes bbatsov/zenburn-emacs#285.
Signed-off-by: kballou <kballou@devnulllabs.io>
> Add some initial cperl custom faces

- zenburn-theme.el
Also make final colors be calculated on the fly; it's annoying to have to `C-M-x` `cider-colors-alist` after modifying `cider-default-colors-alist` or `cider-override-colors-alist`.
> Make `zenburn-override-colors-alist` a customizable variable

- README.md
In 4b3e541 the colour customization mechanism
`zenburn-override-colors-alist`was changed from a `defvar` to a
`defcustom`, which means these instructions need updating.
Fixes #302.
> Fix docs to suggest using customize-set-variable instead of defvar

- zenburn-theme.el
If it's not explicitely set, the face gets an ugly yellow inherited
from the default palette which hurts the eyes (I see it constantly in
notmuch while reading e-mail).
Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>
> Fix widget-field face on 24bit color text terminals

- zenburn-theme.el
Emacs 26.1 introduced built-in line numbers via `display-line-numbers-mode`. This adds support for related faces. I took the colors to closely match vim's zenburn.
> Support for line-numbers-mode

- zenburn-theme.el
https://github.com/tarsius/paren-face/
The modification to show-paren-match is necessary to stop the background colour hiding the dimmed parenthesis. It does change the behaviour with, for example, rainbow-delimiters, but IMO, the effect is actually nicer this way.
> Add parenthesis colour for paren-face

- zenburn-theme.el
While working on #315 I also tested how that interacts with byte-compiling.
Well, the first thing I learned that byte-compiling theme libraries is indeed a bad idea.
But I also got some byte-compile warnings that probably nobody has seen for a while:
```
zenburn-theme.el:36:1:Warning: defgroup for ‘zenburn-theme’ fails to specify
containing group
zenburn-theme.el:169:1:Error: Symbol’s value as variable is void: zenburn-default-colors-alist
``` 
This commit addresses the first of these two (see below).
The second could be fixed by wrapping the respective `defvar` with `(cl-eval-when (eval load compile) ...)`, but since we *don't* byte-compile, that's not really necessary.
----
I don't think it is customary to add theme groups to any parent group,
but that's probably just because themes are …
> Add zenburn-theme to faces Custom group

- zenburn-theme.el
A new face was recently added to swiper:
https://github.com/abo-abo/swiper/commit/39a9e94d530c3d209f367e1aefe313b696100248
This is how it looks without this change:
And this is with this PR applied:
I only changed the foreground colour a little, but if you need me to work on the background instead, just let me know.
> Theme swiper-isearch-current-match

- zenburn-theme.el
`swiper-isearch-current-match` has been removed from Swiper.
See: https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/131
> Theme swiper-line-face

- zenburn-theme.el
I have replaced the color of font faces with their corresponding value in Zenburn theme (`blue` becomes `zenburn-blue`, etc)
> Theme customize interface (cus-edit.el)

- zenburn-theme.el
Seeing that Centaur Tabs is a growing package (I personally love it!), I've added the following color support for it.
```
;;;;; Centaur Tabs
`(centaur-tabs-default ((t (:background ,zenburn-bg :foreground ,zenburn-fg+1))))
`(centaur-tabs-selected ((t (:background ,zenburn-bg :foreground "white"))))
`(centaur-tabs-unselected ((t (:background ,zenburn-bg-1 :foreground "#909090"))))
`(centaur-tabs-selected-modified ((t (:background ,zenburn-bg :foreground ,"#bbbbbb"))))
`(centaur-tabs-unselected-modified ((t (:background ,zenburn-bg-1 :foreground ,"#909090"))))
`(centaur-tabs-active-bar-face ((t (:background ,zenburn-yellow))))
`(centaur-tabs-modified-marker-selected ((t (:inherit 'centaur-tabs-selected-modified :foreground ,zenburn-yellow-1))))
`(centaur-tabs-modified-marker-unselected ((t …
```
> Add support for centaur-tabs, doom-modeline, and solaire-mode

- zenburn-theme.el
For now this is just food for thought and a place to talk.
While working on fixing a regression introduced by #300 I found myself once more longing for better tooling when editing themes. Beside this I also wrote https://github.com/tarsius/kludges/blob/master/kludges.el#L30.
Anyway, don't merge this (yet?), I intend to look into implementing a generalized variant, that could be used by other themes as well.
----
I originally implemented these advices in #106.  They got commented
out in 27cee3d in response to #110 and similar reports in prelude's
issue tracker.
I just implemented the same thing again, only to find the commented
advices once I was done... five years later... it seem I would very
much like this.
So I had a look at the reports and it seems pretty obvious what the
issue was: …
> Uncomment and fix the advices that add zenburn-specific font-lock

- zenburn-theme.el
Yes, the variable's symbol prefix really doesn't match the name of the
package.
> Add display-fill-column-indicator support

- zenburn-theme.el
In Emacs 27, to make a face extend to the full line, you need the extend property. This commit fixes that. More information here: https://www.reddit.com/r/emacs/comments/diahh1/emacs_27_update_changed_how_highlighted_lines/
Best regards,
Stefan Kangas
- [? - seems to be missing] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
Thanks!
> Fix hl-line-mode on Emacs 27

- zenburn-theme.el
Add `org-block` face, controlling:
#+BEGIN_SRC c
int foo = 42;
#+END_SRC
Add `org-quote`, controlling:
#+BEGIN_QUOTE
abc
#+END_QUOTE
Note that the quote block fontification is off until you customize `org-fontify-quote-and-verse-blocks` to a non-nil value.
> Add org-block and org-quote faces

- zenburn-theme.el
Same thing as #335 but for the region face - we need to add the :extend attribute.
> Fix region face on Emacs 27

- zenburn-theme.el
Fix helm header face on Emacs 27.
Same as #335 but for helm headers
Thanks!
> Fix helm header face on Emacs 27

- README.md
- zenburn-theme.el
The options listed below were removed from the customize interface since they don't take effect when using `custom-set-variables` as described on issue #325.
```elisp
zenburn-use-variable-pitch
zenburn-scale-org-headlines
zenburn-scale-outline-headlines
```
Also changed the docstring and the README.md to reflect this.
Thanks!
> Remove options that do not take effect when using custom-set-variable from the customize interface

- zenburn-theme.el
* Use defcustom instead of defvar for `zenburn-add-font-lock-keywords`.
* Change group prefix from `zenburn-theme-` to `zenburn-`.
Thanks!
contribution guidelines is not found...?
> Make zenburn-add-font-lock-keywords customizable

- zenburn-theme.el
When `persp-selected-face` inherits mode-line like this, the wrong face is used on inactive modelines. Dropping the `:inherit mode-line` works correctly for active and inactive modelines.
This issue was first reported to me as gonewest818/dimmer.el#39, however in debugging I found the issue was in the definition of the face and not, per se, an issue with `dimmer` or `perspective`.
Thanks!
> persp-selected-face should not inherit mode-line

- zenburn-theme.el
More info: https://en.wikipedia.org/wiki/Wikipedia:Zenburn
> Make zenburn numbers blue (according to official specs)

- zenburn-theme.el
This PR adds `elfeed-search-title-face` and `elfeed-search-unread-title-face`, which are used to show feed's title in Elfeed search buffer.
Both faces were unspecified in zenburn, and the default is a bit too bright, and not distinct enough for read and unread feeds.
After my change:
Thanks!
> Add elfeed-search-title-face and elfeed-search-unread-title-face

- CHANGELOG.md
- zenburn-theme.el
Add helm-ff-file-extension face (introduced with Helm v3.6.4) to prevent file extension within helm-find-files defaulting to magenta.
> Add helm-ff-file-extension

- zenburn-theme.el
This adds faces for [`vertico`](https://github.com/minad/vertico) and [`orderless`](https://github.com/oantolin/orderless). The face for current selection in `vertico` is made identical to `ivy-current-match`. The faces for `orderless` are selected from the zenburn palette to match the default ones defined in the `orderless`.
Before:
After:
> Add support for vertico and orderless

- CHANGELOG.md
- zenburn-theme.el
Default face for rmail-header-name is font-lock-function-name-face.
Before:
After:
> Add RMAIL faces

- CHANGELOG.md
- zenburn-theme.el
I note that there is already bbatsov/zenburn-emacs#354.  I have kept the same unobtrusive style, using a bold weight to further highlight the active tab.  (I experimented with using green+1 / green-2 ala powerline, but I think I prefer the muted appearance).  I'm also using the box style, similar to the mode-line.
Before:
After:
Thanks!
> Adding support for tab-bar-mode

- zenburn-theme.el
This PR adds new flymake colors based on the existing legacy flymake color schema:
Before
After
Thanks!
> Add new flymake color

- CHANGELOG.md
- zenburn-theme.el
Basic faces are the same as SLIME. For sly-stickers, only
sly-stickers-placed-face needs to be set, as the other ones only inherit from
hi-blue, hi-pink and hi-green.
Before:
After:
Thanks!
> Add SLY faces

- CHANGELOG.md
- zenburn-theme.el
Adds basic support for tab-line-mode. Uses the same styling as tab-bar-mode.
Before:
After:
Thanks!
> Add tab-line-mode support

- CHANGELOG.md
- zenburn-theme.el
I am the author of the "window-tool-bar" package which was recently added to Emacs 30. I'm now chasing down popular themes so that it looks good when Emacs 30 is released.
* Before: ![before](https://github.com/bbatsov/zenburn-emacs/assets/9546385/b6929cbe-d7d1-452a-b8e0-1c4085be0840)
* After: ![after](https://github.com/bbatsov/zenburn-emacs/assets/9546385/68beefdd-b484-4011-b117-304ae0c76d24)
* Note: No configuration added
> Add support for window-tool-bar, added in Emacs 30.
